services:
  api:
    build: .
    container_name: mercatorio_api
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:14
    container_name: mercatorio_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
