"""renomeando tabelas e colunas

Revision ID: 48150beb8a2d
Revises: 
Create Date: 2025-05-20 08:44:56.505334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48150beb8a2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credores')
    op.drop_table('precatorios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precatorios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('credor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero_precatorio', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('valor_nominal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('foro', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data_publicacao', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['credor_id'], ['credores.id'], name='precatorios_credor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='precatorios_pkey')
    )
    op.create_table('credores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cpf_cnpj', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='credores_pkey')
    )
    # ### end Alembic commands ###
